### PR TITLE
Add a 'maybe' option to event attendance so that people can indicate …

### PR DESCRIPTION
**Pull request by melange396**
…interest without committing to the event.

I'm not sure how you want to do the DB migration, but you'd just need to remove the 'NOT NULL' constraint on the 'attending' column of the 'user_event' table.
I must also admit that this is untested.

### CODE REVIEW

**Comment by jgayfer** [comment]
First of all, thanks for the PR! Much appreciated.

I have some feedback:

- For migrations, simply drop a `.sql` file in `db/migrations`, and it will automatically be applied. Magic!
- I don't really like that we're using `null` to indicated a 'maybe'; it's pretty hacky. I would prefer if we went ahead and used an integer instead for example, and have 1=accepted, 2=declined, 3=maybe. Null represents the absence of something, and we shouldn't use it to represent a specific value.
- I would much prefer if this was tested first :) Just saves some time on my end.

Thanks again for all your hard work!

**Comment by melange396** [comment]
You're welcome, but it wasn't much work; it was mostly copypasta.  NULL here does sorta represent the absence of something -- its the absence of a decision on the part of the user!

I can make the changes you want very shortly, but it will be a long while before I will have the time to set up a full testing instance.

**Comment by jgayfer** [comment]
@melange396 I pulled this down today to give it a try. There were some issues, all of which I haven't explored. I would rather you take a look yourself and flesh things out (no time pressure, I get it!). I just wanted to point out that the migration file needs to have a number (my bad for not telling you this). It won't work as is, but if you rename the migration file to `event_maybes0000.sql` it will work!

**Comment by jgayfer** [comment]
Just a heads up that this is a feature I would love to merge in. However, I'm going to finish it off myself unless some work is done here. Just giving you a heads up!

**Comment by melange396** [comment]
👍

**Pull request merged**
